### ISSUE TITLE
Project be continue ?

### ISSUE THREAD

**Issue by end1an** [jacksonrayhamilton/tabany#1]
I need to test your project but i can not to download http://tabany.zxq.net/images.tar.gz file.
Can you help me pls.

**Comment by jacksonrayhamilton** [comment]
Well, I can't log onto the zxq.net account anymore, and the demo is down (as is nodejitsu), and I can't find the images on my computer. But I searched for some of the file names (from the JSON configurations scattered around) and I found the ["winter" tileset](http://s274.photobucket.com/user/BRevolution/media/Breeze%20Revolution%20Templates/Breeze%20Revolution%20Sprites/Breeze%20Revolution%20Tilesets/Gratheo-breezeicyyj9.png.html?sort=3&o=21) and the [character sprites](http://s155.photobucket.com/user/greensoft/library/brcharacters?sort=3&page=1). That might help you find the rest yourself. Also, I'd happily accept a PR adding them to the repo.

**Comment by jacksonrayhamilton** [comment]
Good news, I finally found the images.  I just went ahead and added them to the repo in https://github.com/jacksonrayhamilton/tabany/commit/d93861b8dbad6ba022832d40e3f7571845415529.
